
export const MPKK_LIST = [
  "MPKK BERTAM INDAH",
  "MPKK PMTG TINGGI B",
  "MPKK PAYA KELADI",
  "MPKK LADANG MALAKOFF",
  "MPKK PMTG LANGSAT",
  "MPKK PINANG TUNGGAL",
  "MPKK KG BAHARU",
  "MPKK KUBANG MENERONG",
  "MPKK KG TOK BEDU",
  "MPKK KG SELAMAT RANGKAIAN",
  "MPKK KG SELAMAT SELATAN",
  "MPKK JALAN KEDAH",
  "MPKK KG DATUK",
  "MPKK PMTG SINTOK",
  "MPKK PMTG RAMBAI",
  "MPKK PADANG BENGGALI",
  "MPKK KUALA MUDA"
] as const;

export const JAWATAN_LIST = [
  "Pengerusi",
  "Setiausaha",
  "Bendahari"
] as const;
