CREATE TABLE IF NOT EXISTS registrations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    no_tel VARCHAR(20) NOT NULL,
    no_ic VARCHAR(20) NOT NULL,
    mpkk VARCHAR(100) NOT NULL,
    jawatan VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
